mysqlite_path: "data/db_name.db"
gemini_api_key: "key"
gemini_api_url: "https://..."
articles_in_post: 3

prompts:
  scoring: "You are a strict technical expert. Score the news from 1 to 10..."
  enrichment: "You are a tech journalist. Read the article content. Translate its title to Ukrainian. Choose one highly relevant emoji. Write a concise, engaging summary in 3-4 sentences in Ukrainian. Provide 3-5 relevant short tags (e.g., ai, space, tech)...."

filters:
  blacklist:
    - datafeed: "hackaday"
      categories: ["other", "politics"]

telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN_HERE"
  main_channel_id: "-1000000000000"
  debug_channel_id: "-1000000000001"

feeds:
  - name: "hackaday"
    url: "https://hackaday.com/blog/feed/"
    poll_interval_min: 60
    content_selector: "div.entry-content p" # Specific selector